# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Azure Pipelines
steps:
  - task: Docker@0
    displayName: 'build image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: DockerHub
      dockerFile: deploy.production.dockerfile

  - task: Docker@0
    displayName: 'push image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: DockerHub
      action: 'Push an image'
